language: node_js

node_js:
  - 13.14.0

cache : 
   directories: 
   -'node_modules'

install: 
   -yarn add

services:
-mongodb

env:
 global:
- NODE_ENV=test

before_script:
  - npm install -g 

script: 
 -yarn test

after_success: 
 - echo "Done"